version: '3'

networks:
  my_network:
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../:/var/www/html
    depends_on:
      - php73
      - php8
      - php83
    networks:
      my_network:
        ipv4_address: 172.18.0.2

  php73:
    build:
      context: .
      dockerfile: Dockerfile-php73
    volumes:
      - ../:/var/www/html
    extra_hosts:
      - "localhost.lc:172.18.0.2"
      - "talentics-app.lc:172.18.0.2"
      - "talentics-console.lc:172.18.0.2"
      - "talentics-core.lc:172.18.0.2"
      - "talentics-site.lc:172.18.0.2"
      - "talentics-jobs.lc:172.18.0.2"
    networks:
      my_network:
        ipv4_address: 172.18.0.3

  php8:
    build:
      context: .
      dockerfile: Dockerfile-php8
    volumes:
      - ../:/var/www/html
    extra_hosts:
      - "localhost.lc:172.18.0.2"
      - "talentics-app.lc:172.18.0.2"
      - "talentics-console.lc:172.18.0.2"
      - "talentics-core.lc:172.18.0.2"
      - "talentics-site.lc:172.18.0.2"
      - "talentics-jobs.lc:172.18.0.2"
    networks:
      my_network:
        ipv4_address: 172.18.0.4

  php82:
      build:
        context: .
        dockerfile: Dockerfile-php82
      volumes:
        - ../:/var/www/html
      extra_hosts:
        - "localhost.lc:172.18.0.2"
        - "talentics-app.lc:172.18.0.2"
        - "talentics-console.lc:172.18.0.2"
        - "talentics-core.lc:172.18.0.2"
        - "talentics-site.lc:172.18.0.2"
        - "talentics-jobs.lc:172.18.0.2"
      networks:
        my_network:
          ipv4_address: 172.18.0.5

  php83:
      build:
        context: .
        dockerfile: Dockerfile-php83
      volumes:
        - ../:/var/www/html
      extra_hosts:
        - "localhost.lc:172.18.0.2"
        - "vac-dashboard.lc:172.18.0.2"
      networks:
        my_network:
          ipv4_address: 172.18.0.6