FROM php:8.2-fpm

WORKDIR /var/www/html

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        gcc \
        make \
        autoconf \
        libc-dev \
        pkg-config \
        zlib1g-dev \
        libcurl4-openssl-dev \
        libjson-c-dev \
        libssl-dev \
        libz-dev \
        libxml2-dev \
        libzip-dev \
        libpng-dev \
        libjpeg-dev

# Install PHP extensions individually
RUN docker-php-ext-install opcache && docker-php-ext-enable opcache
RUN docker-php-ext-install curl
RUN docker-php-ext-install session
RUN docker-php-ext-install pdo
RUN docker-php-ext-install pdo_mysql
RUN docker-php-ext-install dom
RUN docker-php-ext-install zip
RUN docker-php-ext-install xml
RUN docker-php-ext-install mysqli

RUN docker-php-ext-configure gd --with-jpeg && \
    docker-php-ext-install gd

# PHP Config .ini
COPY ./config/opcache.ini /usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
# COPY ./config/xdebug.ini /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
COPY ./config/php.ini /usr/local/etc/php/

# Copy application files
COPY . /var/www/html
