FROM php:8.0-fpm

WORKDIR /var/www/html

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        gcc \
        make \
        autoconf \
        libc-dev \
        pkg-config \
        zlib1g-dev \
        libcurl4-openssl-dev \
        libjson-c-dev \
        libssl-dev \
        libz-dev \
        libxml2-dev \
        libzip-dev \
        libpng-dev \
        libjpeg-dev

RUN docker-php-ext-install opcache \
    && docker-php-ext-enable opcache \
    && pecl install xdebug \
    && docker-php-ext-enable xdebug \
    && docker-php-ext-install curl \
    session pdo pdo_mysql tokenizer dom zip \
    xml mysqli

RUN docker-php-ext-configure gd --with-jpeg && \
    docker-php-ext-install gd

# Install Node.js 12.x
RUN curl -fsSL https://deb.nodesource.com/setup_12.x | bash - && \
    apt install -y nodejs

# PHP Config .ini
COPY ./config/opcache.ini /usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
COPY ./config/xdebug.ini /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
COPY ./config/php.ini /usr/local/etc/php/

# Copy application files
COPY . /var/www/html
