version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/var/www/html
    depends_on:
      - php73
      - php8

  php73:
    build:
      context: .
      dockerfile: Dockerfile-php73
    volumes:
      - ./html:/var/www/html

  php8:
    build:
      context: .
      dockerfile: Dockerfile-php8
    volumes:
      - ./html:/var/www/html
